name: Africa Talking USSD Lambdas

on:
  push:

jobs:
  lambda_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: gi${{ secrets.AWS_SECRET_ACCESS_PASS }}
          aws-region: us-east-1

      - name: Zip Lambda function
        run: zip -j Africas-Talking-USSD-18790ae4-5e17-4217-acfb-e9572fe0c55c.zip ./index.js

      - name: Update Lambda function code
        run: aws lambda update-function-code --function-name=lambda1 --zip-file fileb://Africas-Talking-USSD-18790ae4-5e17-4217-acfb-e9572fe0c55c.zip

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Approval
    steps:
      - name: Placeholder for deployment steps
        run: echo "Deployment steps go here"
